name: "FlyCI macOS"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_macos-arm64:
    name: go${{ matrix.go }} (macos/arm64)
    strategy:
      matrix:
        go: [ "1.20", "1.21" ] # we support the latest 2 stable versions of Go
    runs-on: flyci-macos-large-latest-m1 # generously provided by www.flyci.net
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}.x # use latest patch version under the minor version
    - run: go version
    - name: Build and Test
      run:  |
        go build -v ./...
        go test -v ./...